### ISSUE TITLE
Shift to Git LFS for deployment of large binary files

### ISSUE THREAD

**Issue by wei2912** [wei2912/gamedesign-js#7]
https://git-lfs.github.com/?utm_source=github_site&utm_medium=blog&utm_campaign=gitlfs

I am trying to get early access for this feature. Hopefully I'll succeed.

**Comment by d10** [comment]
What large binaries do we have?

**Comment by wei2912** [comment]
@d10 None as of now, but it'd be good to commit all binary files using this system. A lot better than committing directly.
